services:
  - type: worker
    name: topcoinbuyerbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: "1943851828"
      - key: SUPPORT_USERNAME
        value: "sabbirvai007"
